POST http://localhost:4000/api/projects
Content-Type: application/json

{
    "name": "safeway",
    "website": "https://safeway-two.vercel.app/",
    "technologies": "Typescript, Next, Tailwindcss",
    "github": "https://github.com/pedroalima/safeway"
}

###
POST http://localhost:4000/api/home
Content-Type: application/json

{
    "username": "colossoxd",
    "password": "123456789"
}

###
GET http://localhost:4000/api/users

###
GET http://localhost:4000/api/projects

###
GET http://localhost:4000/api/projects/65919fd921b89e4139afd569

###
DELETE http://localhost:4000/api/projects/65919fd921b89e4139afd569

###
PUT http://localhost:4000/api/projects/659076f01ae65f447312966d
Content-Type: application/json

{
    "name": "safeway",
    "website": "https://safeway-two.vercel.app/",
    "technologies": "Typescript, Next, Tailwindcss",
    "github": "https://github.com/pedroalima/safeway"
}